CREATE TABLE RouteRoles (
  RoleId BIGINT NOT NULL,
  RouteId BIGINT NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(RoleId, RouteId),
  FOREIGN KEY (RoleId) REFERENCES Roles(id),
  FOREIGN KEY (RouteId) REFERENCES Routes(id)
);
